project:
  type: website

website:
  title: "another-intro-r"
  sidebar:
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Home
      - 1.getting_started.qmd
      - 2.calculateR.qmd
      - 3.file_types.qmd
      - 4.dataframes.qmd
      - 5.working_with_data.qmd 
      - 6.data_vis.qmd
      - 7.stats_n_probs.qmd

format:
  html:
    theme:
      - united
    css: styles.css
    toc: true

editor: visual

